### ISSUE TITLE
Items spawn system

### ISSUE THREAD

**Issue by zakaos** [zakaos/opentxtgame#21]
When makeRoom function is executed, if an item has a startingroom value that matches the current room, and the item is not in the players inventory, add item to room description.

**Comment by hyeri0609** [comment]
How about add items[] array for each room and put item inside it? the makeRoom function will check if there are items inside the array then display it, this way we dont need 'startingroom' property.

Anyway, if you want to keep items together outside room, we might consider to have initial function which will be called once at very beginning to loop in items array and put it in each room, this way we still need 'startingroom' property (just for beginning state) and also still need items[] array inside each room.

if you consider items can be dropped, the solution above can support.
but if you dont want to add items[] array inside room and support dropping, we might consider to have 'room' property instead of 'startingRoom' to describe where each items stay at the current

**Comment by zakaos** [comment]
ahhh i see what you mean. It sounds like the only way to make it possible would be to create an array of items for each room, which would support dropping items, as well as having each item having a property of location which would describe which room it was in, as well as a location placeholder for inventory, so it would merge with the inventory system.

**Comment by zakaos** [comment]
your code is perfect thos is exactly the functionality required!
